export const propertiesData = [
  {
    id: 1,
    name: "4791 Claire Dr",
    slug: "4791-claire-dr",
    type: "Shared & Private",
    price: "Contact for pricing",
    location: "4791 Claire Dr Oceanside, CA 92057",
    image: "/properties/House%20Photos/4791-claire-dr/Screenshot%202026-05-27%20051850.jpg",
    amenities: ["Large Backyard", "High-Speed Wi-Fi", "Weekly Cleaning"],
    description: "A beautiful home located in a quiet Oceanside neighborhood, offering both shared and private rooms. Enjoy a spacious backyard and a welcoming community atmosphere.",
  },
  {
    id: 2,
    name: "4798 Claire Dr",
    slug: "4798-claire-dr",
    type: "Shared & Private",
    price: "Contact for pricing",
    location: "4798 Claire Dr Oceanside, CA 92057",
    image: "/properties/House%20Photos/4798-claire-dr/Screenshot%202026-05-27%20055156.jpg",
    amenities: ["En-suite Bathrooms", "Community Kitchen", "Security System", "Near Public Transit"],
    description: "Comfortable and accessible living on Claire Dr. This home features modern amenities, a secure environment, and excellent access to local transit options.",
  },
  {
    id: 3,
    name: "608 Ann St",
    slug: "608-ann-st",
    type: "Shared & Private",
    price: "Contact for pricing",
    location: "608 Ann St Oceanside, CA 92057",
    image: "/properties/House%20Photos/608-ann-st/Screenshot%202026-05-27%20052833.jpg",
    amenities: ["Furnished Living Area", "All Utilities Included", "On-site Laundry", "Patio Deck"],
    description: "Centrally located on Ann St, this residence boasts a fully furnished living area and a wonderful patio deck for relaxing outdoors.",
  },
  {
    id: 4,
    name: "649 Parker St",
    slug: "649-parker-st",
    type: "Shared & Private",
    price: "Contact for pricing",
    location: "649 Parker St Oceanside, CA 92057",
    image: "/properties/House%20Photos/649-parker-st/Screenshot%202026-05-27%20054826.jpg",
    amenities: ["All Utilities Included", "On-site Laundry", "Patio Deck"],
    description: "Enjoy peaceful living on Parker St with all utilities included. This property offers comprehensive amenities and a supportive community.",
  },
  {
    id: 5,
    name: "640 Parker St Unit B",
    slug: "640-parker-st",
    type: "Shared & Private",
    price: "Contact for pricing",
    location: "640 Parker St Unit B Oceanside, CA 92057",
    image: "/properties/House%20Photos/640-parker-st/Screenshot%202026-05-27%20054519.jpg",
    amenities: ["Furnished Living Area", "All Utilities Included", "On-site Laundry", "Patio Deck"],
    description: "A cozy and inviting unit on Parker St. Designed with comfort in mind, it provides a superb independent living experience.",
  },
  {
    id: 6,
    name: "755 Arthur",
    slug: "755-arthur-ave",
    type: "Shared & Private",
    price: "Contact for pricing",
    location: "755 Arthur Oceanside, CA 92057",
    image: "/properties/House%20Photos/755-arthur-ave/Screenshot%202026-05-27%20053739.jpg",
    amenities: ["En-suite Bathrooms", "Community Kitchen", "Security System", "Near Public Transit"],
    description: "Located on Arthur Ave, this house features a great community kitchen, secure premises, and close proximity to Oceanside's best amenities.",
  },
  {
    id: 7,
    name: "627 Flora Dr",
    slug: "627-flora-drive",
    type: "Shared & Private",
    price: "Contact for pricing",
    location: "627 Flora Dr Oceanside, CA 92057",
    image: "/properties/House%20Photos/627-flora-drive/Screenshot%202026-05-27%20052936.jpg",
    amenities: ["Furnished Living Area", "All Utilities Included", "On-site Laundry", "Patio Deck"],
    description: "Flora Drive offers a serene setting with a fully furnished layout, making it an ideal choice for comfortable, independent living.",
  },
  {
    id: 8,
    name: "4823 Sol Sitio",
    slug: "4823-sol-sitio",
    type: "Shared & Private",
    price: "Contact for pricing",
    location: "4823 Sol Sitio Oceanside, CA 92057",
    image: "/properties/House%20Photos/4823-sol-sitio/Screenshot%202026-05-27%20052556.jpg",
    amenities: ["Large Backyard", "High-Speed Wi-Fi", "Weekly Cleaning"],
    description: "Sol Sitio is a premium property featuring a huge backyard, accessible facilities, and a robust community support system.",
  },
  {
    id: 9,
    name: "616 Monica Cir",
    slug: "616-monica-circle",
    type: "Shared & Private",
    price: "Contact for pricing",
    location: "616 Monica Cir Oceanside, CA 92057",
    image: "/properties/House%20Photos/616-monica-circle/Screenshot%202026-05-27%20054012.jpg",
    amenities: ["Furnished Living Area", "All Utilities Included", "On-site Laundry", "Patio Deck"],
    description: "Situated on Monica Circle, this property provides a fantastic balance of privacy and shared community spaces, complete with a lovely patio.",
  },
  {
    id: 10,
    name: "610 Monica Cir",
    slug: "610-monica-circle",
    type: "Shared & Private",
    price: "Contact for pricing",
    location: "610 Monica Cir Oceanside, CA 92057",
    image: "/properties/House%20Photos/610-monica-circle/Screenshot%202026-05-27%20054339.jpg",
    amenities: ["En-suite Bathrooms", "Community Kitchen", "Security System", "Near Public Transit"],
    description: "A secure and welcoming home on Monica Circle. Residents enjoy great shared amenities and easy access to public transportation.",
  }
];
